var tricks = {
	novice_def: {name: 'novice_def', caption: 'Прикрыться', 
		action: 'Следующий удар по вам нанесет на 3 ед. меньше урона.', school: 'fight',
		delay: 3,		
	},
	novice_hit: {name: 'novice_hit', caption: 'Вломить', 
		action: 'Следующий удар наносит на 4 ед. больше урона.', school: 'fight',
		delay: 4,
	},
	novice_hp: {name: 'novice_hp', caption: 'Собрать Зубы', 
		action: 'Вы восстанавливаете от 2-5 НР.', school: 'fight',
		delay: 4,
	},
	block_absolute: {name: 'block_absolute', caption: 'Абсолютная защита', 
		action: 'До Вашего следующего размена ударами, все повреждения от оружия или магии по Вам сводятся к 1.', school: 'fight',
		required: {level:7},
		resources: {block:7}
	},
	block_fullshield: {name: 'block_fullshield', caption: 'Полная защита', 
		action: 'Следующий удар или заклятие нанесет вам не более 1 повреждения.', school: 'fight',
		required: {level:5},
		resources: {block:5}
	},
	block_activeshield: {name: 'block_activeshield', caption: 'Активная защита', 
		action: 'Следующий удар или заклятие нанесет вам лишь половину повреждений.', school: 'fight',
		required: {level:3},
		resources: {block:3}
	},
	block_addchange: {name: 'block_addchange', caption: 'Выбор противника', 
		action: 'Дополнительная смена противника.', school: 'fight',
		required: {level:2},
		resources: {block:1}
	},
	block_target: {name: 'block_target', caption: 'Защитить', 
		action: 'Следующий удар по защищаемой цели попадает по защитнику.<br /><i>Требует наличия щита.</i>', school: 'fight',
		required: {level:8,endurance:35},
		resources: {block:2},
		delay: 8,
	},
	block_aftershock: {name: 'block_aftershock', caption: 'Контузия', 
		action: 'Оглушает противника ударом щита, нанося 5-20 урона, лишая его возможности использовать последний применённый приём на пять ходов.<br><i>Требует наличия щита.</i>', school: 'fight',
		required: {level:5},
		resources: {block:2},
		delay: 8,
	},
	block_restore: {name: 'block_restore', caption: 'Глухая Защита', 
		action: 'Вы восстанавливаете 15%HP за 6 ходов, урон по Вам падает на 25%,<br />ваш урон падает вдвое.<br /><i>Требует наличия щита.</i>', school: 'fight',
		required: {level:6,strength:30,endurance:30},
		resources: {block:10,spirit:3},
		delay: 12,
	},
	/*block_target_shield: {name: 'block_target_shield', caption: 'Живой щит', description: 'Предложить себя в качестве живого щита на один ход. Если кто-то использует на вас прием Живой меч, то нанесет удар по противнику вместо вас.', school: 'fight',
		required: {level:8,endurance:30},
		resources: {block:1}
	},*/
	block_magicshield: {name: 'block_magicshield', caption: 'Магическая Защита', 
		action: 'Следующее заклятие нанесет вам не более 1 повреждения, защита действует не более трех ходов.', school: 'fight',
		required: {level:7},
		resources: {block:3}
	},
	block_revenge: {name: 'block_revenge', caption: 'Возмездие', 
		action: 'Противник, нанесший вам удар, получит (12 x Ваш уровень) ед. урона.<i>Требует наличия щита.</i>', school: 'fight',
		required: {level:7},
		resources: {block:5}
	},
	block_path: {name: 'block_path', caption: 'Путь Щита', 
		action: 'Увеличивает ваш мф. против критического удара на 50 и снижает весь получаемый урон на 5%. Можно применять трижды.<br /><i>Требует наличия щита.</i>', school: 'fight',
		required: {level:7},
		resources: {block:5},
		delay: 1,

	},
	spirit_11_prot_100: {name: 'spirit_11_prot_100', caption: 'Призрачный Кинжал', 
		action: 'Уменьшает колющий урон на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_12_prot_100: {name: 'spirit_12_prot_100', caption: 'Призрачный Топор', 
		action: 'Уменьшает рубящий урон на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_13_prot_100: {name: 'spirit_13_prot_100', caption: 'Призрачный Удар', 
		action: 'Уменьшает дробящий урон на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_14_prot_100: {name: 'spirit_14_prot_100', caption: 'Призрачное Лезвие', 
		action: 'Уменьшает режущий урон на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_1_protfire100: {name: 'spirit_1_protfire100', caption: 'Призрачный Огонь', 
		action: 'Уменьшает урон от Магии Огня на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_2_protwater100: {name: 'spirit_2_protwater100', caption: 'Призрачная Вода', 
		action: 'Уменьшает урон от Магии Воды на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_3_protair100: {name: 'spirit_3_protair100', caption: 'Призрачный Воздух', 
		action: 'Уменьшает урон от Магии Воздуха на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_4_protearth100: {name: 'spirit_4_protearth100', caption: 'Призрачная Земля', 
		action: 'Уменьшает урон от Магии Земли на 50% на 3 хода.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:5}
	},
	spirit_block25: {name: 'spirit_block25', caption: 'Призрачная защита', 
		action: 'До вашего следующего размена ударами, вы получаете лишь четверть повреждений от оружия или магии.', school: 'fight',
		required: {level:7},
		resources: {},
		delay: 5,
		consumes: {spiritlevel:10}
	},
	spirit_survive: {name: 'spirit_survive', caption: 'Выжить', 
		action: 'Исцеляет вас, используя все набранные вами тактики.<br />Использовать прием можно 1 раз за бой.<br />После использования все тактики пропадают.<br />Прием восстанавливает не более 25% НР. 1 тактика - 1% НР, 1<img src="' + baseImgPath+ 'hp.gif"> - 0.5%НР', school: 'fight',
		required: {level:7,endurance:30},
		resources: {},
		consumes: {spiritlevel:10}
	},
	hit_strong: {name: 'hit_strong', caption: 'Сильный удар', 
		action: 'Следующий удар наносит на 3*(Ваш уровень) ед. урона больше.', school: 'fight',
		required: {level:2},
		resources: {hit:3}
	},
	hit_luck: {name: 'hit_luck', caption: 'Удачный удар', 
		action: 'Следующий удар наносит на 6*(Ваш уровень) ед. урона больше.', school: 'fight',
		required: {level:4},
		resources: {hit:5}
	},
	hit_overhit: {name: 'hit_overhit', caption: 'Подлый удар', 
		action: 'Мгновенно наносит противнику 5*(уровень) ед. урона.', school: 'fight',
		required: {level:4},
		resources: {hit:7},
		consumes: {spiritlevel:1}
	},
	hit_restrike: {name: 'hit_restrike', caption: 'Прорыв', 
		action: 'Мгновенно наносит противнику треть урона оружием, игнорируя любую защиту.', school: 'fight',
		required: {level:8,strength:45},
		resources: {hit:9},
		delay: 5,
		consumes: {spiritlevel:1}
	},
	hit_resolve: {name: 'hit_resolve', caption: 'Разведка боем', 
		action: 'Успешное попадание раскрывает тактику противника, пять ходов показывая все его усиления и приемы', school: 'fight',
		required: {level:5},
		delay: 5,
		resources: {hit:3}
	},
	hit_shock: {name: 'hit_shock', caption: 'Ошеломить', exclusiveWarrior: true,
		action: 'Оглушает противника, лишая его возможности<br />использовать приемы на 2 хода, нанося 5-10 урона.<br />Противник получает иммунитет к ошеломлению на 5 ходов.<br />Нельзя использовать, если мудрость больше 39', school: 'fight',
		required: {level:7,strength:25},
		resources: {hit:3},
		delay: 5
	},
	/*hit_target_sword: {name: 'hit_target_sword', caption: 'Живой меч', description: 'Нанести удар вместо союзника решившего стать живым щитом. Требуется цель с приемом Живой щит.', school: 'fight',
		required: {level:8,strength:50},
		resources: {hit:3}
	},*/
	blood_gainattack: {name: 'blood_gainattack', caption: 'Рывок', exclusiveWarrior: true,
		action: 'Ослабляя свою защиту и повышая урон<br />(Защита от урона: -250, Мф. мощности урона: +25),<br />вы прорываетесь к противнику и получаете <img src="' + baseImgPath + 'hit.gif" width=8 height=8> 3', school: 'fight',
		resources: {},
		required: {level:7,strength:25,endurance:25}
	},
	hit_willpower: {name: 'hit_willpower', caption: 'Воля к победе', 
		action: 'Вы восстанавливаете 5*(уровень)+7 HP, эффект увеличен на 25%, если ваши HP ниже 33%', school: 'fight',
		required: {level:3},
		resources: {hit:5},
		consumes: {spiritlevel:1}
	},
	hit_empower: {name: 'hit_empower', caption: 'Усиленные удары', 
		action: 'Все удары в следующем размене наносят на 5*(Уровень) ед. урона больше.', school: 'fight',
		required: {level:7},
		resources: {hit:3}
	},
	krit_wildluck: {name: 'krit_wildluck', caption: 'Дикая удача', 
		action: 'Следующий критический удар наносит максимальные повреждения.', school: 'fight',
		required: {level:3},
		resources: {krit:3}
	},
	krit_blindluck: {name: 'krit_blindluck', caption: 'Слепая удача', 
		action: 'Следующий удар будет критическим. Вы не получите очки "Критических ударов" с этого крита.', school: 'fight',
		required: {level:5},
		resources: {krit:5}
	},
	krit_crush: {name: 'krit_crush', caption: 'Сокрушающий удар', 
		action: 'Ваш следующий удар нанесет двойной урон.', school: 'fight',
		required: {level:7},
		resources: {krit:7}
	},
	krit_blooddrink: {name: 'krit_blooddrink', caption: 'Хлебнуть Крови', 
		action: 'Следующий критический удар лечит вас частью нанесенного урона.<br />Выпитая кровь придает вам силы.', school: 'fight',
		required: {level:6},
		resources: {krit:7,block:3},
		consumes: {spiritlevel:2}
	},
	krit_bloodlust: {name: 'krit_bloodlust', caption: 'Жажда Крови', 
		action: 'Увеличивает ваш мф. критического удара на 50 до конца боя<br />и увеличивает физический урон на 5%.<br />Можно применять трижды.', school: 'fight',
		required: {level:7},
		resources: {hit:2,krit:3}
	},
	counter_winddance: {name: 'counter_winddance', caption: 'Танец ветра', 
		action: 'Вы увернетесь от следующего направленного в вас удара. Вы не получите очки "Контрудара" за контрудар с этого уворота.', school: 'fight',
		required: {level:3},
		resources: {counter:3},
		delay: 3,
	},
	counter_bladedance: {name: 'counter_bladedance', caption: 'Танец лезвий', 
		action: 'Вы увернетесь от следующего направленного в вас удара и нанесете контрудар. Вы не получите очки "Контрудара" за контрудар с этого уворота.', school: 'fight',
		required: {level:5},
		resources: {counter:5},
		delay: 3,
	},
	counter_ward: {name: 'counter_ward', caption: 'Осторожность', 
		action: 'Уменьшает урон от магии стихий вдвое на три хода.', school: 'fight',
		required: {level:7,dexterity:25},
		resources: {counter:2},
		delay: 5,
	},
	counter_deathwalk: {name: 'counter_deathwalk', caption: 'Поступь Смерти', 
		action: 'Увеличивает максимальный урон оружием на 1*(Уровень).<br />Каждый успешный удар увеличивает макс. урон еще на 1*(Уровень) ед., до 10*(Уровень)<br />и обновляет время эффекта. Эффект длится два хода.', school: 'fight',
		required: {level:7},
		resources: {counter:5}
	},
	parry_prediction: {name: 'parry_prediction', caption: 'Предвидение', 
		action: 'Следующий удар противника парируется.<br />Вы не получите очки "Парирования" за это парирование.', school: 'fight',
		required: {level:3},
		resources: {parry:3}
	},
	parry_secondlife: {name: 'parry_secondlife', caption: 'Второе дыхание', 
		action: 'Следующий удар противника - парируется,<br />за каждый уровень противника, чей удар вы парировали, вы получаете 5НР.<br />Вы не получите очки "Парирования" за это парирование.', school: 'fight',
		required: {level:5},
		resources: {parry:5},
		consumes: {spiritlevel:2}
	},
	parry_supreme: {name: 'parry_supreme', caption: 'Превосходство', exclusiveWarrior: true,
		action: 'Увеличивает ваш мф. против критического удара и мф. против увертывания на 25 до конца боя. Снижает урон от магии на 5%.<br />Можно применять трижды.<br />Требует 25 ловкости.', school: 'fight',
		required: {level:7, dexterity: 25},
		resources: {block:1,parry:3},
		delay: 1,
	},
	multi_hitshock: {name: 'multi_hitshock', caption: 'Шокирующий удар', exclusiveWarrior: true,
		action: 'Ваше следующее попадание оглушает противника, лишая его возможности использовать приемы и получать очки тактики на два хода.<br />Нельзя использовать, если мудрость больше 39', school: 'fight',
		required: {level:7},
		resources: {hit:3,counter:1},
		delay: 6,
	},
	multi_agressiveshield: {name: 'multi_agressiveshield', caption: 'Агрессивная защита', 
		action: 'Следующий удар или заклятие противника нанесет не более 1 повреждения,<br />противник получает (3 x Ваш уровень) ед. урона.<br .>Защищает от приемов Разгадать Тактику и Ставка на опережение.', school: 'fight',
		required: {level:7},
		resources: {hit:2,block:5}
	},
	multi_blockchanges: {name: 'multi_blockchanges', caption: 'Ограничить маневр', 
		action: 'Количество смен противника у текущей цели становится равным 0.', school: 'fight',
		required: {level:5},
		resources: {hit:1,block:2},
		delay: 1,
	},
	multi_cowardshift: {name: 'multi_cowardshift', caption: 'Коварный уход', 
		action: 'Следующий удар противника наносится по нему, вместо вас.<br />Требует 50 ловкости.', school: 'fight',
		required: {level:7,dexterity: 50},
		resources: {counter:5,block:2}
	},
	multi_doom: {name: 'multi_doom', caption: 'Обречённость', 
		action: 'Шанс увернуться от вашего удара, парировать или отбить его щитом снижен на 25% на 3 хода.', school: 'fight',
		required: {level:5},
		resources: {hit:2,block:3},
		delay: 5,
	},
	multi_followme: {name: 'multi_followme', caption: 'Преследование', exclusiveWarrior: true,
		action: 'Целью противника становитесь вы.<br />Боец не в праве менять противника, до тех пор,<br />пока не разменяется ударом с вами.', school: 'fight',
		required: {level:5},
		resources: {hit:3,block:2},
		delay: 20,
	},
	multi_hiddendodge: {name: 'multi_hiddendodge', caption: 'Скрытая ловкость', 
		action: 'Вы уворачиваетесь от следующего удара по вам и наносите контрудар.', school: 'fight',
		required: {level:6},
		resources: {krit:3,block:2}
	},
	multi_hiddenpower: {name: 'multi_hiddenpower', caption: 'Скрытая сила', 
		action: 'Следующий ваш удар - критический.', school: 'fight',
		required: {level:6},
		resources: {hit:3,counter:4},
		delay: 5,
	},
	multi_resolvetactic: {name: 'multi_resolvetactic', caption: 'Разгадать тактику', 
		action: 'Отменяет все активные приемы на текущем бойце при размене ударами.<br />Не работает на монстрах.', school: 'fight',
		required: {level:5},
		resources: {hit:1,block:2},
		delay: 8,
	},
	multi_skiparmor: {name: 'multi_skiparmor', caption: 'Точный удар', 
		action: 'Следующий ваш удар игнорирует броню противника<br />И снижает сопротивление урону на 250ед., но не ниже 0.', school: 'fight',
		required: {level:5},
		resources: {hit:5,counter:1,parry:2}
	},
	multi_speedup: {name: 'multi_speedup', caption: 'Ставка на опережение', 
		action: 'При размене ударами вы украдете все активные приемы на противнике.', school: 'fight',
		required: {level:7},
		resources: {hit:3,counter:3},
		delay: 8,
	},
	multi_rollback: {name: 'multi_rollback', caption: 'Отменить', 
		action: 'Отменяет последнее полученное повреждение или лечение.<br />Можно применять трижды за бой.', school: 'fight',
		required: {level:7,strength:25,endurance:25},
		resources: {hit:2,block:2},
		delay: 15
	},
	hp_circleshield: {name: 'hp_circleshield', caption: 'Круговая защита', 
		action: 'Урон, наносимый вашей команде, уменьшен на 1 до конца боя.', school: 'fight',
		required: {level:4,endurance:10},
		resources: {hp:10},
		delay: 10,
	},
	hp_natisk: {name: 'hp_natisk', caption: 'Натиск', 
		action: 'Урон, наносимый вашей командой, увеличен на 1 до конца боя.', school: 'fight',
		required: {level:4,endurance:10},
		resources: {hp:10},
		delay: 10,
	},
	hp_cleance: {name: 'hp_cleance', caption: 'Очиститься кровью', 
		action: 'Снимает один негативный эффект от магии, болезни или отравления', school: 'fight',
		required: {level:7},
		resources: {hp:1},
		delay: 5
	},
	hp_defence: {name: 'hp_defence', caption: 'Стойкость', 
		action: 'Увеличивает вашу защиту от урона на (5%) до конца боя. Можно применять трижды.', school: 'fight',
		required: {level:4},
		resources: {hp:5}
	},
	hp_enrage: {name: 'hp_enrage', caption: 'Ярость', 
		action: 'Увеличивает ваш урон на (5%) до конца боя. Можно применять трижды.', school: 'fight',
		required: {level:4},
		resources: {hp:5}
	},
	hp_laststrike: {name: 'hp_laststrike', caption: 'Последний удар', 
		action: 'Ценой всей силы духа увеличивает урон на один удар.<br />Нанеся удар вы погибаете.', school: 'fight',
		required: {level:4},
		resources: {hp:10},
		consumes: {spiritlevel:'100%'}
	},
	hp_regen: {name: 'hp_regen', caption: 'Утереть пот', 
		action: 'Вы восстанавливаете 2*ваш уровень ХП. Сила Духа не тратится.', school: 'fight',
		required: {level:2},
		resources: {hp:5}
	},
	hp_travma: {name: 'hp_travma', caption: 'Искалечить', 
		action: 'По окончанию боя, противник может получить травму при поражении. Не работает на монстрах.', school: 'fight',
		required: {level:5},
		resources: {hp:10}
	},
	/*hp_trade: {name: 'hp_trade', caption: 'Разделить Кровь', description: 'Цель получает <img width=8 height=8 src="hp.gif">1', school: 'fight',
		required: {level:7},
		resources: {hp:3}
	},*/
	wis_air_chaincure05: {name: 'wis_air_chaincure05', caption: 'Цепь Исцеления [5]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-126 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {level:5,intellect:20,airmagicskill:5},
		resources: {hp:1},
		consumes: {mana:46},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:126}
	},
	wis_air_chaincure06: {name: 'wis_air_chaincure06', caption: 'Цепь Исцеления [6]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-152 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {level:6,intellect:30,airmagicskill:6},
		resources: {hp:1},
		consumes: {mana:69},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:152}
	},
	wis_air_chaincure07: {name: 'wis_air_chaincure07', caption: 'Цепь Исцеления [7]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-183 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		resources: {hp:1},
		consumes: {mana:104},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:183}
	},
	wis_air_chaincure08: {name: 'wis_air_chaincure08', caption: 'Цепь Исцеления [8]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-219 HP магией Воздуха.', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		resources: {hp:1},
		consumes: {mana:124},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:219}
	},
	wis_air_chaincure09: {name: 'wis_air_chaincure09', caption: 'Цепь Исцеления [9]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-263 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		resources: {hp:1},
		consumes: {mana:149},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:263}
	},
	wis_air_chaincure10: {name: 'wis_air_chaincure10', caption: 'Цепь Исцеления [10]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-316 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {level:10,intellect:75,airmagicskill:10},
		resources: {hp:1},
		consumes: {mana:179},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:316}
	},
	wis_air_chaincure11: {name: 'wis_air_chaincure11', caption: 'Цепь Исцеления [11]', spendsMove : true,
		action: 'Восстанавливает 1-3 целям 1-380 HP магией Воздуха.', iname: 'wis_air_chaincure08', school: 'air',
		required: {intellect:100,airmagicskill:11,level:11},
		resources: {hp:1},
		consumes: {mana:215},
		delay: 3,
		healing: {mincount:1,maxcount:3,minhitpoints:1,maxhitpoints:380}
	},
	wis_air_chainlight06: {name: 'wis_air_chainlight06', caption: 'Цепь Молний [6]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-46 урона электричеством.', iname: 'wis_air_chainlight08', school: 'air',
		required: {level:6,intellect:30,airmagicskill:6},
		consumes: {mana:71},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:46}
	},
	wis_air_chainlight07: {name: 'wis_air_chainlight07', caption: 'Цепь Молний [7]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-55 урона электричеством.', iname: 'wis_air_chainlight08', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		consumes: {mana:107},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:55}
	},
	wis_air_chainlight08: {name: 'wis_air_chainlight08', caption: 'Цепь Молний [8]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-67 урона электричеством.', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		consumes: {mana:128},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:67}
	},
	wis_air_chainlight09: {name: 'wis_air_chainlight09', caption: 'Цепь Молний [9]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-81 урона электричеством.', iname: 'wis_air_chainlight08', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		consumes: {mana:154},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:81}
	},
	wis_air_chainlight10: {name: 'wis_air_chainlight10', caption: 'Цепь Молний [10]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-97 урона электричеством.', iname: 'wis_air_chainlight08', school: 'air',
		required: {level:10,intellect:75,airmagicskill:10},
		consumes: {mana:185},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:97}
	},
	wis_air_chainlight11: {name: 'wis_air_chainlight11', caption: 'Цепь Молний [11]', spendsMove : true,
		action: 'Наносит 2-5 целям 1-116 урона электричеством.', iname: 'wis_air_chainlight08', school: 'air',
		required: {level:11,intellect:100,airmagicskill:11},
		consumes: {mana:222},
		delay: 3,
		attack: {mincount:2,maxcount:5,mindamage:1,maxdamage:116}
	},
	wis_air_shaft04: {name: 'wis_air_shaft04', caption: 'Молния [4]', spendsMove : true,
		action: 'Наносит цели 1-55 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:4,intellect:15,airmagicskill:4},
		consumes: {mana:15},
		delay: 1,
		attack: {mindamage:1,maxdamage:55}
	},
	wis_air_shaft05: {name: 'wis_air_shaft05', caption: 'Молния [5]', spendsMove : true,
		action: 'Наносит цели 1-66 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:5,intellect:20,airmagicskill:5},
		consumes: {mana:23},
		delay: 1,
		attack: {mindamage:1,maxdamage:66}
	},
	wis_air_shaft06: {name: 'wis_air_shaft06', caption: 'Молния [6]', spendsMove : true,
		action: 'Наносит цели 1-79 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:6,intellect:30,airmagicskill:6},
		consumes: {mana:34},
		delay: 1,
		attack: {mindamage:1,maxdamage:79}
	},
	wis_air_shaft07: {name: 'wis_air_shaft07', caption: 'Молния [7]', spendsMove : true,
		action: 'Наносит цели 1-97 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		consumes: {mana:52},
		delay: 1,
		attack: {mindamage:1,maxdamage:97}
	},
	wis_air_shaft08: {name: 'wis_air_shaft08', caption: 'Молния [8]', spendsMove : true,
		action: 'Наносит цели 1-115 урона электричеством', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		consumes: {mana:62},
		delay: 1,
		attack: {mindamage:1,maxdamage:115}
	},
	wis_air_shaft09: {name: 'wis_air_shaft09', caption: 'Молния [9]', spendsMove : true,
		action: 'Наносит цели 1-139 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		consumes: {mana:74},
		delay: 1,
		attack: {mindamage:1,maxdamage:139}
	},
	wis_air_shaft10: {name: 'wis_air_shaft10', caption: 'Молния [10]', spendsMove : true,
		action: 'Наносит цели 1-167 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:10,intellect:75,airmagicskill:10},
		consumes: {mana:89},
		delay: 1,
		attack: {mindamage:1,maxdamage:167}
	},
	wis_air_shaft11: {name: 'wis_air_shaft11', caption: 'Молния [11]', spendsMove : true,
		action: 'Наносит цели 1-200 урона электричеством', iname: 'wis_air_shaft08', school: 'air',
		required: {level:11,intellect:100,airmagicskill:11},
		consumes: {mana:107},
		delay: 1,
		attack: {mindamage:1,maxdamage:200}
	},
	wis_air_sparks08: {name: 'wis_air_sparks08', caption: 'Искры [8]', 
		action: 'Наносит 1-7 целям 1-54 урона электричеством', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		consumes: {mana:117},
		delay: 16,
		attack: {mincount:1,maxcount:7,mindamage:1,maxdamage:54}
	},
	wis_air_sparks09: {name: 'wis_air_sparks09', caption: 'Искры [9]', 
		action: 'Наносит 1-7 целям 1-66 урона электричеством', iname: 'wis_air_sparks08', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		consumes: {mana:140},
		delay: 16,
		attack: {mincount:1,maxcount:7,mindamage:1,maxdamage:66}
	},
	wis_air_sparks10: {name: 'wis_air_sparks10', caption: 'Искры [10]', 
		action: 'Наносит 1-7 целям 1-79 урона электричеством', iname: 'wis_air_sparks08', school: 'air',
		required: {level:10,intellect:75,airmagicskill:10},
		consumes: {mana:168},
		delay: 16,
		attack: {mincount:1,maxcount:7,mindamage:1,maxdamage:79}
	},
	wis_air_sparks11: {name: 'wis_air_sparks11', caption: 'Искры [11]', 
		action: 'Наносит 1-7 целям 1-95 урона электричеством', iname: 'wis_air_sparks08', school: 'air',
		required: {level:11,intellect:100,airmagicskill:11},
		consumes: {mana:202},
		delay: 16,
		attack: {mincount:1,maxcount:7,mindamage:1,maxdamage:95}
	},
	wis_air_mark: {name: 'wis_air_mark', caption: 'Цель Воздуха', 
		action: 'Уменьшает сопротивляемость воздействию Магии Воздуха. Можно применить на одну цель до 5 раз.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		resources: {},
		delay: 1,
		consumes: {mana:20,spiritlevel:0.5}
	},
	wis_air_sign: {name: 'wis_air_sign', caption: 'Знак Воздуха', 
		action: 'Маг получает 10 маны каждый ход.<br>Стоимость всех заклинаний снижена на 3%.', school: 'air',
		required: {level:4,intellect:25,airmagicskill:2},
		resources: {},
		consumes: {mana:11,spiritlevel:1}
	},
	wis_air_shield07: {name: 'wis_air_shield07', caption: 'Туманный Образ [7]', 
		action: 'Все атаки по вам в следующем размене будут отражены в случайного союзника (в том числе и в вас).<br>Прием не подвержен действию шока.', iname: 'wis_air_shield08', school: 'air',
		required: {level:7,intellect:20,airmagicskill:7},
		resources: {hp:1},
		delay: 8,
		consumes: {mana:80}
	},
	wis_air_shield08: {name: 'wis_air_shield08', caption: 'Туманный Образ [8]', 
		action: 'Следующая атака по вам будет отражена в случайного противника или союзника.<br>Прием не подвержен действию шока.', school: 'air',
		required: {level:8,intellect:40,airmagicskill:8},
		resources: {hp:1},
		delay: 8,
		consumes: {mana:160}
	},
	wis_air_shield09: {name: 'wis_air_shield09', caption: 'Туманный Образ [9]', 
		action: 'Следующая атака по вам будет отражена в случайного противника.<br>Прием не подвержен действию шока.', iname: 'wis_air_shield08', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		resources: {hp:1},
		delay: 8,
		consumes: {mana:240}
	},
	wis_air_shield10: {name: 'wis_air_shield10', caption: 'Туманный Образ [10]', 
		action: 'Следующая атака по вам будет отражена обратно в атакующего.<br>Прием не подвержен действию шока.', iname: 'wis_air_shield08', school: 'air',
		required: {level:10,intellect:80,airmagicskill:10},
		resources: {hp:1},
		delay: 8,
		consumes: {mana:240}
	},
	wis_earth_gravity07: {name: 'wis_earth_gravity07', caption: 'Гравитация [7]', spendsMove: true,
		action: 'Наносит цели 10% урона магией Земли от ее текущего уровня жизни. Заклинание не может нанести более 170ед. урона. урона.', iname: 'wis_earth_gravity08', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		delay: 3,
		consumes: {mana:65}
	},
	wis_earth_gravity08: {name: 'wis_earth_gravity08', caption: 'Гравитация [8]', spendsMove: true,
		action: 'Наносит цели 10% урона магией Земли от её текущего уровня жизни. Заклинание не может нанести более 204ед. урона.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 3,
		consumes: {mana:78}
	},
	wis_earth_gravity09: {name: 'wis_earth_gravity09', caption: 'Гравитация [9]', spendsMove: true,
		action: 'Наносит цели 10% урона магией Земли от её текущего уровня жизни. Заклинание не может нанести более 244ед. урона.', iname: 'wis_earth_gravity08', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		delay: 3,
		consumes: {mana:93}
	},
	wis_earth_gravity10: {name: 'wis_earth_gravity10', caption: 'Гравитация [10]', spendsMove: true,
		action: 'Наносит цели 10% урона магией Земли от её текущего уровня жизни. Заклинание не может нанести более 293ед. урона.', iname: 'wis_earth_gravity08', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		delay: 3,
		consumes: {mana:112}
	},
	wis_earth_gravity11: {name: 'wis_earth_gravity11', caption: 'Гравитация [11]', spendsMove: true,
		action: 'Наносит цели 10% урона магией Земли от её текущего уровня жизни. Заклинание не может нанести более 352ед. урона.', iname: 'wis_earth_gravity08', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		delay: 3,
		consumes: {mana:134}
	},
	wis_earth_heal05: {name: 'wis_earth_heal05', caption: 'Дух Природы [5]', spendsMove: true,
		action: 'Восстанавливает 5 целям 14HP магией земли и 30НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:5,intellect:20,earthmagicskill:5},
		resources: {hp:1},
		consumes: {mana:23},
		delay: 1,
		healing: {count:5,hitpoints:14,selfhitpoints:30}
	},
	wis_earth_heal06: {name: 'wis_earth_heal06', caption: 'Дух Природы [6]', spendsMove: true,
		action: 'Восстанавливает 5 целям 17HP магией земли и 35НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:6,intellect:30,earthmagicskill:6},
		resources: {hp:1},
		consumes: {mana:34},
		delay: 1,
		healing: {count:5,hitpoints:17,selfhitpoints:35}
	},
	wis_earth_heal07: {name: 'wis_earth_heal07', caption: 'Дух Природы [7]', spendsMove: true,
		action: 'Восстанавливает 5 целям 21HP магией земли и 43НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		resources: {hp:1},
		consumes: {mana:52},
		delay: 1,
		healing: {count:5,hitpoints:21,selfhitpoints:43}
	},
	wis_earth_heal08: {name: 'wis_earth_heal08', caption: 'Дух Природы [8]', spendsMove: true,
		action: 'Восстанавливает 5 целям 25HP магией земли и 51НР себе.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		resources: {hp:1},
		consumes: {mana:78},
		delay: 1,
		healing: {count:5,hitpoints:25,selfhitpoints:51}
	},
	wis_earth_heal09: {name: 'wis_earth_heal09', caption: 'Дух Природы [9]', spendsMove: true,
		action: 'Восстанавливает 5 целям 30HP магией земли и 62НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		resources: {hp:1},
		consumes: {mana:93},
		delay: 1,
		healing: {count:5,hitpoints:30,selfhitpoints:62}
	},
	wis_earth_heal10: {name: 'wis_earth_heal10', caption: 'Дух Природы [10]', spendsMove: true,
		action: 'Восстанавливает 5 целям 37HP магией земли и 75НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		resources: {hp:1},
		consumes: {mana:112},
		delay: 1,
		healing: {count:5,hitpoints:37,selfhitpoints:75}
	},
	wis_earth_heal11: {name: 'wis_earth_heal11', caption: 'Дух Природы [11]', spendsMove: true,
		action: 'Восстанавливает 5 целям 45HP магией земли и 90НР себе.', iname: 'wis_earth_heal08', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		resources: {hp:1},
		consumes: {mana:134},
		delay: 1,
		healing: {count:5,hitpoints:45,selfhitpoints:90}
	},
	wis_earth_meteor06: {name: 'wis_earth_meteor06', caption: 'Метеорит [6]', spendsMove: true,
		action: 'Наносит цели 61-65 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:6,intellect:30,earthmagicskill:6},
		consumes: {mana:17},
		delay: 3,
		attack: {mindamage:61,maxdamage:65}
	},
	wis_earth_meteor07: {name: 'wis_earth_meteor07', caption: 'Метеорит [7]', spendsMove: true,
		action: 'Наносит цели 73-78 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		consumes: {mana:26},
		delay: 3,
		attack: {mindamage:73,maxdamage:78}
	},
	wis_earth_meteor08: {name: 'wis_earth_meteor08', caption: 'Метеорит [8]', spendsMove: true,
		action: 'Наносит цели 87-95 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		consumes: {mana:31},
		delay: 3,
		attack: {mindamage:87,maxdamage:94}
	},
	wis_earth_meteor09: {name: 'wis_earth_meteor09', caption: 'Метеорит [9]', spendsMove: true,
		action: 'Наносит цели 105-114 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		consumes: {mana:37},
		delay: 3,
		attack: {mindamage:105,maxdamage:114}
	},
	wis_earth_meteor10: {name: 'wis_earth_meteor10', caption: 'Метеорит [10]', spendsMove: true,
		action: 'Наносит цели 126-136 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		consumes: {mana:44},
		delay: 3,
		attack: {mindamage:126,maxdamage:136}
	},
	wis_earth_meteor11: {name: 'wis_earth_meteor11', caption: 'Метеорит [11]', spendsMove: true,
		action: 'Наносит цели 151-164 урона через три хода.', iname: 'wis_earth_meteor08', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		consumes: {mana:53},
		delay: 3,
		attack: {mindamage:151,maxdamage:164}
	},
	wis_earth_rain05: {name: 'wis_earth_rain05', caption: 'Каменный Дождь [5]', spendsMove: true,
		action: 'Наносит 8 целям 9 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:5,intellect:20,earthmagicskill:5},
		consumes: {mana:52},
		delay: 1,
		attack: {count:8,damage:9}
	},
	wis_earth_rain06: {name: 'wis_earth_rain06', caption: 'Каменный Дождь [6]', spendsMove: true,
		action: 'Наносит 8 целям 11 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:6,intellect:30,earthmagicskill:6},
		consumes: {mana:78},
		delay: 1,
		attack: {count:8,damage:11}
	},
	wis_earth_rain07: {name: 'wis_earth_rain07', caption: 'Каменный Дождь [7]', spendsMove: true,
		action: 'Наносит 8 целям 14 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		consumes: {mana:117},
		delay: 1,
		attack: {count:8,damage:14}
	},
	wis_earth_rain08: {name: 'wis_earth_rain08', caption: 'Каменный Дождь [8]', spendsMove: true,
		action: 'Наносит 8 целям 17 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		consumes: {mana:140},
		delay: 1,
		attack: {count:8,damage:17}
	},
	wis_earth_rain09: {name: 'wis_earth_rain09', caption: 'Каменный Дождь [9]', spendsMove: true,
		action: 'Наносит 8 целям 21 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		consumes: {mana:168},
		delay: 1,
		attack: {count:8,damage:21}
	},
	wis_earth_rain10: {name: 'wis_earth_rain10', caption: 'Каменный Дождь [10]', spendsMove: true,
		action: 'Наносит 8 целям 25 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		consumes: {mana:197},
		delay: 1,
		attack: {count:8,damage:19}
	},
	wis_earth_rain11: {name: 'wis_earth_rain11', caption: 'Каменный Дождь [11]', spendsMove: true,
		action: 'Наносит 8 целям 30 урона магией земли', iname: 'wis_earth_rain08', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		consumes: {mana:197},
		delay: 1,
		attack: {count:8,damage:30}
	},
	wis_earth_mark: {name: 'wis_earth_mark', caption: 'Цель Земли', 
		action: 'Уменьшает сопротивляемость воздействию Магии Земли. Можно применить на одну цель до 5 раз.', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		delay: 1,
		consumes: {mana:20,spiritlevel:0.5}
	},
	wis_earth_sign: {name: 'wis_earth_sign', caption: 'Знак Земли', 
		action: 'Цель получает +2 брони, т.е. 5 интеллекта = +2 брони. Заклинание требует 10 маны каждый ход.', school: 'earth',
		required: {level:4,intellect:25,earthmagicskill:1},
		resources: {},
		consumes: {mana:110,spiritlevel:1}
	},
	wis_earth_strike07: {name: 'wis_earth_strike07', caption: 'Каменный Удар [7]', spendsMove: true,
		action: 'Наносит цели 113 ед. дробящего урона.', iname: 'wis_earth_strike', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		consumes: {mana:94},
		delay: 3,
		attack: {damage:113}
	},
	wis_earth_strike08: {name: 'wis_earth_strike08', caption: 'Каменный Удар [8]', spendsMove: true,
		action: 'Наносит цели 134 ед. дробящего урона.', iname: 'wis_earth_strike', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:7},
		consumes: {mana:113},
		delay: 3,
		attack: {damage:134}
	},
	wis_earth_strike09: {name: 'wis_earth_strike09', caption: 'Каменный Удар [9]', spendsMove: true,
		action: 'Наносит цели 155 ед. дробящего урона.', iname: 'wis_earth_strike', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:7},
		consumes: {mana:120},
		delay: 3,
		attack: {damage:155}
	},
	wis_earth_strike10: {name: 'wis_earth_strike10', caption: 'Каменный Удар [10]', spendsMove: true,
		action: 'Наносит цели 176 ед. дробящего урона.', iname: 'wis_earth_strike', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:7},
		consumes: {mana:130},
		delay: 3,
		attack: {damage:176}
	},
	wis_earth_cleance: {name: 'wis_earth_cleance', caption: 'Коснуться Земли', 
		action: 'Снимает один негативный эффект от магии или болезни и восстанавливает 3% маны.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 5,
		consumes: {mana:50}
	},
	wis_earth_dmg04: {name: 'wis_earth_dmg04', caption: 'Булыжник [4]', spendsMove: true,
		action: 'Наносит цели 22-25 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:4,intellect:15,earthmagicskill:4},
		consumes: {mana:11},
		delay: 1,
		attack: {mindamage:22,maxdamage:25}
	},
	wis_earth_dmg05: {name: 'wis_earth_dmg05', caption: 'Булыжник [5]', spendsMove: true,
		action: 'Наносит цели 26-30 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:5,intellect:20,earthmagicskill:5},
		consumes: {mana:17},
		delay: 1,
		attack: {mindamage:26,maxdamage:30}
	},
	wis_earth_dmg06: {name: 'wis_earth_dmg06', caption: 'Булыжник [6]', spendsMove: true,
		action: 'Наносит цели 31-37 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:6,intellect:30,earthmagicskill:6},
		consumes: {mana:26},
		delay: 1,
		attack: {mindamage:31,maxdamage:37}
	},
	wis_earth_dmg07: {name: 'wis_earth_dmg07', caption: 'Булыжник [7]', spendsMove: true,
		action: 'Наносит цели 38-45 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		consumes: {mana:39},
		delay: 1,
		attack: {mindamage:38,maxdamage:45}
	},
	wis_earth_dmg08: {name: 'wis_earth_dmg08', caption: 'Булыжник [8]', spendsMove: true,
		action: 'Наносит цели 46-54 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		consumes: {mana:46},
		delay: 1,
		attack: {mindamage:46,maxdamage:54}
	},
	wis_earth_dmg09: {name: 'wis_earth_dmg09', caption: 'Булыжник [9]', spendsMove: true,
		action: 'Наносит цели 57-65 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		consumes: {mana:56},
		delay: 1,
		attack: {mindamage:57,maxdamage:65}
	},
	wis_earth_dmg10: {name: 'wis_earth_dmg10', caption: 'Булыжник [10]', spendsMove: true,
		action: 'Наносит цели 67-78 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		consumes: {mana:67},
		delay: 1,
		attack: {mindamage:67,maxdamage:78}
	},
	wis_earth_dmg11: {name: 'wis_earth_dmg11', caption: 'Булыжник [11]', spendsMove: true,
		action: 'Наносит цели 82-94 урона магией земли.', iname: 'wis_earth_dmg08', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		consumes: {mana:80},
		delay: 1,
		attack: {mindamage:82,maxdamage:94}
	},
	wis_earth_flower8: {name: 'wis_earth_flower8', caption: 'Каменный Цветок [8]', spendsMove: true,
		action: 'Цель получает 58 урона магией земли и лишается возможности использовать приемы 1 ход.<br>Еще 3 цели получают 19 урона магией земли', iname: 'wis_earth_flower', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		resources: {hp:1},
		consumes: {mana:128},
		delay: 3,
		attack: {count:3,damage:58}
	},
	wis_earth_flower9: {name: 'wis_earth_flower9', caption: 'Каменный Цветок [9]', spendsMove: true,
		action: 'Цель получает 69 урона магией земли и лишается возможности использовать приемы 1 ход. <br>Еще 3 цели получают 23 урона магией земли', iname: 'wis_earth_flower', school: 'earth',
		required: {level:9,intellect:60,earthmagicskill:9},
		resources: {hp:1},
		consumes: {mana:154},
		delay: 3,
		attack: {count:3,damage:69}
	},
	wis_earth_flower10: {name: 'wis_earth_flower10', caption: 'Каменный Цветок [10]', spendsMove: true,
		action: 'Цель получает 83 урона магией земли и лишается возможности использовать приемы 1 ход.<br> Еще 3 цели получают 29 урона магией земли', iname: 'wis_earth_flower', school: 'earth',
		required: {level:10,intellect:75,earthmagicskill:10},
		resources: {hp:1},
		consumes: {mana:185},
		delay: 3,
		attack: {count:3,damage:83}
	},
	wis_earth_flower11: {name: 'wis_earth_flower11', caption: 'Каменный Цветок [11]', spendsMove: true,
		action: 'Цель получает 101 урона магией земли и лишается возможности использовать приемы 1 ход.<br> Еще 3 цели получают 34 урона магией земли', iname: 'wis_earth_flower', school: 'earth',
		required: {level:11,intellect:100,earthmagicskill:11},
		resources: {hp:1},
		consumes: {mana:222},
		delay: 3,
		attack: {count:3,damage:101}
	},
	wis_earth_link_minus: {name: 'wis_earth_link_minus', caption: 'Заземление: Минус', 
		action: 'Цель теряет 79 маны за 10 ходов.<br />Разные виды Заземления заменяют друг друга.<br />Маг способен поддерживать лишь одно Заземление.<br />Требует 1 маны каждый ход. Применяется до 5 раз.<br />Прием не подвержен действию шока.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 3,
		consumes: {mana:20}
	},
	wis_earth_link_plus: {name: 'wis_earth_link_plus', caption: 'Заземление: Плюс', 
		action: 'Исцеляет мага на 47HP за 10 ходов за счет жизни цели.<br />Разные виды Заземления заменяют друг друга.<br />Маг способен поддерживать лишь одно Заземление.<br />Требует 5 маны каждый ход. Применяется до 5 раз.<br />Прием не подвержен действию шока.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 3,
		consumes: {mana:20}
	},
	wis_earth_link_zero: {name: 'wis_earth_link_zero', caption: 'Заземление: Ноль', 
		action: 'Увеличивает весь урон по цели на 3% и уменьшает целебные эффекты на 7%.<br />Разные виды Заземления заменяют друг друга.<br />Маг способен поддерживать лишь одно Заземление.<br />Требует 5 маны каждый ход. Применяется до 5 раз.<br />Прием не подвержен действию шока.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 3,
		consumes: {mana:20}
	},
	wis_earth_sacrifice: {name: 'wis_earth_sacrifice', caption: 'Жертва Земле', 
		action: 'Вы восстанавливаете 5% HP и 5% маны.', school: 'earth',
		required: {level:7,intellect:40,earthmagicskill:7},
		resources: {hp:5},
		delay: 5,
		consumes: {mana:5}
	},
	wis_earth_shield: {name: 'wis_earth_shield', caption: 'Каменный Щит', 
		action: 'Вы получаете на 95% меньше урона в этот размен.<br>Прием не подвержен действию шока.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 7,
		consumes: {mana:150}		
	},
	wis_earth_shield2: {name: 'wis_earth_shield2', caption: 'Песчаный Щит', 
		action: 'Вы получаете на 30% меньше урона от магии в течение 5 ходов.<br>Прием не подвержен действию шока.', school: 'earth',
		required: {level:8,intellect:50,earthmagicskill:8},
		delay: 8,
		consumes: {mana:150}
	},
	wis_earth_summon: {name: 'wis_earth_summon', caption: 'Каменный Страж', spendsMove: true,
		action: 'Призывает в бой Каменного Стража для защиты мага. Страж нуждается в N*(уровень игрока) маны каждый ход.', school: 'earth',
		required: {level:8,earthmagicskill:12},
		delay: 20,
		consumes: {mana:200}
	},
	wis_fire_burst08: {name: 'wis_fire_burst08', caption: 'Вспышка [8]', 
		action: 'Мгновенно наносит цели 43 урона огнем.<br />Урон увеличен на 5% за каждую Цель Огня присутствующую на жертве.', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		consumes: {mana:70},
		delay: 8,
		attack: {damage:43}
	},
	wis_fire_burst09: {name: 'wis_fire_burst09', caption: 'Вспышка [9]', 
		action: 'Мгновенно наносит цели 51 урона огнем.<br />Урон увеличен на 5% за каждую Цель Огня присутствующую на жертве.', iname: 'wis_fire_burst08', school: 'fire',
		required: {level:9,intellect:60,firemagicskill:9},
		consumes: {mana:84},
		delay: 8,
		attack: {damage:51}
	},
	wis_fire_burst10: {name: 'wis_fire_burst10', caption: 'Вспышка [10]', 
		action: 'Мгновенно наносит цели 62 урона огнем.<br />Урон увеличен на 5% за каждую Цель Огня присутствующую на жертве.', iname: 'wis_fire_burst08', school: 'fire',
		required: {level:10,intellect:75,firemagicskill:10},
		consumes: {mana:101},
		delay: 8,
		attack: {damage:62}
	},
	wis_fire_burst11: {name: 'wis_fire_burst11', caption: 'Вспышка [11]', 
		action: 'Мгновенно наносит цели 75 урона огнем.<br />Урон увеличен на 5% за каждую Цель Огня присутствующую на жертве.', iname: 'wis_fire_burst08', school: 'fire',
		required: {level:11,intellect:100,firemagicskill:11},
		consumes: {mana:121},
		delay: 8,
		attack: {damage:75}
	},
	wis_fire_heal05: {name: 'wis_fire_heal05', caption: 'Тепло Жизни [5]', 
		action: 'Исцеляет цель на 49-55НР магией огня.<br />Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:5,intellect:20,firemagicskill:5},
		resources: {hp:1},
		consumes: {mana:40},
		delay: 4,
		healing: {minhitpoints:49,maxhitpoints:55}
	},
	wis_fire_heal06: {name: 'wis_fire_heal06', caption: 'Тепло Жизни [6]', 
		action: 'Исцеляет цель на 58-67НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:6,intellect:30,firemagicskill:6},
		resources: {hp:1},
		consumes: {mana:60},
		delay: 4,
		healing: {minhitpoints:58,maxhitpoints:67}
	},
	wis_fire_heal07: {name: 'wis_fire_heal07', caption: 'Тепло Жизни [7]', 
		action: 'Исцеляет цель на 70-81НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		resources: {hp:1},
		consumes: {mana:91},
		delay: 4,
		healing: {minhitpoints:70,maxhitpoints:81}
	},
	wis_fire_heal08: {name: 'wis_fire_heal08', caption: 'Тепло Жизни [8]', 
		action: 'Исцеляет цель на 85-97НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		resources: {hp:1},
		consumes: {mana:109},
		delay: 4,
		healing: {minhitpoints:85,maxhitpoints:97}
	},
	wis_fire_heal09: {name: 'wis_fire_heal09', caption: 'Тепло Жизни [9]', 
		action: 'Исцеляет цель на 102-117НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:9,intellect:60,firemagicskill:9},
		resources: {hp:1},
		consumes: {mana:131},
		delay: 4,
		healing: {minhitpoints:102,maxhitpoints:117}
	},
	wis_fire_heal10: {name: 'wis_fire_heal10', caption: 'Тепло Жизни [10]', 
		action: 'Исцеляет цель на 122-139НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:10,intellect:75,firemagicskill:10},
		resources: {hp:1},
		consumes: {mana:157},
		delay: 4,
		healing: {minhitpoints:122,maxhitpoints:139}
	},
	wis_fire_heal11: {name: 'wis_fire_heal11', caption: 'Тепло Жизни [11]', 
		action: 'Исцеляет цель на 147-168НР магией огня. Эффект выше при применении на себя.', iname: 'wis_fire_heal08', school: 'fire',
		required: {level:11,intellect:100,firemagicskill:11},
		resources: {hp:1},
		consumes: {mana:188},
		healing: {minhitpoints:111,maxhitpoints:127}
	},
	wis_fire_flamming06: {name: 'wis_fire_flamming06', caption: 'Пожирающее Пламя [6]', spendsMove: true,
		action: 'Наносит цели 53 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:6,intellect:30,firemagicskill:6},
		consumes: {mana:38},
		delay: 8,
		attack: {damage:53,nextturns:5}
	},
	wis_fire_flamming07: {name: 'wis_fire_flamming07', caption: 'Пожирающее Пламя [7]', spendsMove: true,
		action: 'Наносит цели 63 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		consumes: {mana:57},
		delay: 8,
		attack: {damage:63,nextturns:5}
	},
	wis_fire_flamming08: {name: 'wis_fire_flamming08', caption: 'Пожирающее Пламя [8]', spendsMove: true,
		action: 'Наносит цели 77 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		consumes: {mana:68},
		delay: 8,
		attack: {damage:77,nextturns:5}
	},
	wis_fire_flamming09: {name: 'wis_fire_flamming09', caption: 'Пожирающее Пламя [9]', spendsMove: true,
		action: 'Наносит цели 91 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:9,intellect:60,firemagicskill:9},
		consumes: {mana:82},
		delay: 8,
		attack: {damage:91,nextturns:5}
	},
	wis_fire_flamming10: {name: 'wis_fire_flamming10', caption: 'Пожирающее Пламя [10]', spendsMove: true,
		action: 'Наносит цели 110 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:10,intellect:75,firemagicskill:10},
		consumes: {mana:98},
		delay: 8,
		attack: {damage:110,nextturns:5}
	},
	wis_fire_flamming11: {name: 'wis_fire_flamming11', caption: 'Пожирающее Пламя [11]', spendsMove: true,
		action: 'Наносит цели 133 урона огнем за пять ходов', iname: 'wis_fire_flamming08', school: 'fire',
		required: {level:11,intellect:100,firemagicskill:11},
		consumes: {mana:118},
		delay: 8,
		attack: {damage:133,nextturns:5}
	},
	wis_fire_incenerate04: {name: 'wis_fire_incenerate04', caption: 'Испепеление [4]', spendsMove: true,
		action: 'Наносит цели 27 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:4,intellect:15,firemagicskill:4},
		consumes: {mana:15},
		delay: 1,
		attack: {damage:27}
	},
	wis_fire_incenerate05: {name: 'wis_fire_incenerate05', caption: 'Испепеление [5]', spendsMove: true,
		action: 'Наносит цели 33 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:5,intellect:20,firemagicskill:5},
		consumes: {mana:23},
		delay: 1,
		attack: {damage:33}
	},
	wis_fire_incenerate06: {name: 'wis_fire_incenerate06', caption: 'Испепеление [6]', spendsMove: true,
		action: 'Наносит цели 39 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:6,intellect:30,firemagicskill:6},
		consumes: {mana:34},
		delay: 1,
		attack: {damage:39}
	},
	wis_fire_incenerate07: {name: 'wis_fire_incenerate07', caption: 'Испепеление [7]', spendsMove: true,
		action: 'Наносит цели 47 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		consumes: {mana:52},
		delay: 1,
		attack: {damage:47}
	},
	wis_fire_incenerate08: {name: 'wis_fire_incenerate08', caption: 'Испепеление [8]', spendsMove: true,
		action: 'Наносит цели 58 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		consumes: {mana:62},
		delay: 1,
		attack: {damage:58}
	},
	wis_fire_incenerate09: {name: 'wis_fire_incenerate09', caption: 'Испепеление [9]', spendsMove: true,
		action: 'Наносит цели 69 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:9,intellect:60,firemagicskill:9},
		consumes: {mana:74},
		delay: 1,
		attack: {damage:69}
	},
	wis_fire_incenerate10: {name: 'wis_fire_incenerate10', caption: 'Испепеление [10]', spendsMove: true,
		action: 'Наносит цели 83 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:10,intellect:75,firemagicskill:10},
		consumes: {mana:89},
		delay: 1,
		attack: {damage:83}
	},
	wis_fire_incenerate11: {name: 'wis_fire_incenerate11', caption: 'Испепеление [11]', spendsMove: true,
		action: 'Наносит цели 101 урона огнем', iname: 'wis_fire_incenerate08', school: 'fire',
		required: {level:11,intellect:100,firemagicskill:11},
		consumes: {mana:94},
		delay: 1,
		attack: {damage:101}
	},
	wis_fire_mark: {name: 'wis_fire_mark', caption: 'Цель Огня', 
		action: 'Уменьшает сопротивляемость воздействию Магии Огня. Можно применить на одну цель до 5 раз.', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		resources: {},
		delay: 1,
		consumes: {mana:20,spiritlevel:0.5}
	},
	wis_fire_sign: {name: 'wis_fire_sign', caption: 'Знак Огня', 
		action: 'Маг получает 2*(ваш уровень) мф. мощности магии стихий. Заклинание требует 10 маны каждый ход.', school: 'fire',
		required: {level:4,intellect:25,firemagicskill:2},
		resources: {},
		consumes: {mana:110,spiritlevel:1}
	},
	wis_fire_flameshock: {name: 'wis_fire_flameshock', caption: 'Пылающий Ужас', 
		action: 'Высвобождает энергию вашего заклятия <img src="images/wis_fire_flamming08.gif" width="40" height="25" border="0"> <b>Пожирающее Пламя</b> на цели.<br />Цель получает 75% оставшегося урона Пожирающего Пламени<br />и не может использовать приемы или набирать очки тактики 2 хода.', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		delay: 10,
		consumes: {mana:83}
	},
	wis_fire_flamedestroy: {name: 'wis_fire_flamedestroy', caption: 'Пылающий взрыв', 
		action: 'Высвобождает энергию вашего заклятия <img src="images/wis_fire_flamming08.gif" width="40" height="25" border="0"> <b>Пожирающее Пламя</b> на цели.<br />Цель и еще 4 случайных цели получает 33% оставшегося урона Пожирающего Пламени магией Огня.', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		consumes: {mana:83}
	},
	wis_fire_flamedeath: {name: 'wis_fire_flamedeath', caption: 'Пылающая смерть', 
		action: 'Высвобождает энергию вашего заклятия <img src="images/wis_fire_flamming08.gif" width="40" height="25" border="0"> <b>Пожирающее Пламя</b> на цели,<br />если её уровень жизни менее 33%.<br />Цель получает 150% оставшегося урона Пожирающего пламени.', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		delay: 5,		
		consumes: {mana:83}
	},
	wis_fire_boost: {name: 'wis_fire_boost', caption: 'Разогрев', spendsMove: true,
		action: 'Ваше следующее огненное заклинание получит +100 мф. мощности Магии Огня. Прием не подвержен шоку.', school: 'fire',
		required: {level:7,intellect:25,firemagicskill:7},
		delay: 5,
		consumes: {mana:25}
	},
	wis_fire_sacrifice: {name: 'wis_fire_sacrifice', caption: 'Жертва огню', 
		action: 'Вы теряете 10%НР, но восстанавливаете 20% маны.', school: 'fire',
		required: {level:7,intellect:40,firemagicskill:7},
		resources: {hp:5},
		delay: 5,
		consumes: {mana:5}
	},
	wis_fire_hiddenpower: {name: 'wis_fire_hiddenpower', caption: 'Скрытое пламя', 
		action: 'Если уровень вашей жизни ниже 33%, то при использовании убирает текущие задержки на заклинаниях школы Огня.<br />Один раз за бой.', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		consumes: {mana:83}
	},
	wis_fire_shield: {name: 'wis_fire_shield', caption: 'Огненный щит', 
		action: 'Вы получаете на 50% меньше урона 2 последующих размена,<br />полученный урон восстанавливает вашу ману.<br />Не подвержен шоку.', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		delay: 8,
		consumes: {mana:150}
	},
	wis_fire_flametongue08: {name: 'wis_fire_flametongue08', caption: 'Язык пламени [8]', spendsMove: true,
		action: 'Наносит цели 5% урона магией Огня от её Максимального уровня жизни<br />и ещё +2% за каждый уровень Цели Огня.<br />Заклинание не может нанести более 200 единиц урона.', iname: 'wis_fire_flametongue', school: 'fire',
		required: {level:8,intellect:50,firemagicskill:8},
		delay: 3,
		consumes: {mana:156}
	},
	wis_fire_flametongue09: {name: 'wis_fire_flametongue09', caption: 'Язык пламени [9]', spendsMove: true,
	 	action: 'Наносит цели 5% урона магией Огня от её Максимального уровня жизни<br />и ещё +2% за каждый уровень Цели Огня.<br />Заклинание не может нанести более 250 единиц урона.', iname: 'wis_fire_flametongue', school: 'fire',
		required: {level:9,intellect:60,firemagicskill:9},
		delay: 3,
		consumes: {mana:187}
	},
	wis_fire_flametongue10: {name: 'wis_fire_flametongue10', caption: 'Язык пламени [10]', spendsMove: true,
		action: 'Наносит цели 5% урона магией Огня от её Максимального уровня жизни<br />и ещё +2% за каждый уровень Цели Огня.<br />Заклинание не может нанести более 300 единиц урона.', iname: 'wis_fire_flametongue', school: 'fire',
		required: {level:10,intellect:75,firemagicskill:10},
		delay: 3,
		consumes: {mana:224}
	},
	wis_water_cloud08: {name: 'wis_water_cloud08', caption: 'Ядовитое Облако [8]', spendsMove: true,
		action: 'Наносит 3-5 целям 35 урона ядом за пять ходов.', iname: 'wis_water_cloud08', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		consumes: {mana:156},
		delay: 10,
		attack: {mincount:3,maxcount:5,nextdamage:35,nextturns:5}
	},
	wis_water_cloud09: {name: 'wis_water_cloud09', caption: 'Ядовитое Облако [9]', spendsMove: true,
		action: 'Наносит 3-5 целям 43 урона ядом за пять ходов.', iname: 'wis_water_cloud08', school: 'water',
		required: {level:9,intellect:60,watermagicskill:9},
		consumes: {mana:187},
		delay: 10,
		attack: {mincount:3,maxcount:5,nextdamage:43,nextturns:5}
	},
	wis_water_cloud10: {name: 'wis_water_cloud10', caption: 'Ядовитое Облако [10]', spendsMove: true,
		action: 'Наносит 3-5 целям 51 урона ядом за пять ходов.', iname: 'wis_water_cloud08', school: 'water',
		required: {level:10,intellect:75,watermagicskill:10},
		consumes: {mana:224},
		delay: 10,
		attack: {mincount:3,maxcount:5,nextdamage:51,nextturns:5}
	},
	wis_water_cloud11: {name: 'wis_water_cloud11', caption: 'Ядовитое Облако [11]', spendsMove: true,
		action: 'Наносит 3-5 целям 62 урона ядом за пять ходов.', iname: 'wis_water_cloud08', school: 'water',
		required: {level:11,intellect:100,watermagicskill:11},
		consumes: {mana:269},
		delay: 10,
		attack: {mincount:3,maxcount:5,nextdamage:62,nextturns:5}
	},
	wis_water_frost04: {name: 'wis_water_frost04', caption: 'Оледенение [4]', spendsMove: true,
		action: 'Мгновенно наносит цели 25 урона и ещё 3 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:4,intellect:15,watermagicskill:4},
		consumes: {mana:17},
		delay: 1,
		attack: {damage:19,nextdamage:3,nextturns:4}
	},
	wis_water_frost05: {name: 'wis_water_frost05', caption: 'Оледенение [5]', spendsMove: true,
		action: 'Мгновенно наносит цели 30 урона и ещё 3 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:5,intellect:20,watermagicskill:5},
		consumes: {mana:26},
		delay: 1,
		attack: {damage:30,nextdamage:3,nextturns:4}
	},
	wis_water_frost06: {name: 'wis_water_frost06', caption: 'Оледенение [6]', spendsMove: true,
		action: 'Мгновенно наносит цели 35 урона и ещё 5 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:6,intellect:30,watermagicskill:6},
		consumes: {mana:39},
		delay: 1,
		attack: {damage:35,nextdamage:5,nextturns:3}
	},
	wis_water_frost07: {name: 'wis_water_frost07', caption: 'Оледенение [7]', spendsMove: true,
		action: 'Мгновенно наносит цели 43 урона и ещё 6 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		consumes: {mana:58},
		delay: 1,
		attack: {damage:43,nextdamage:6,nextturns:4}
	},
	wis_water_frost08: {name: 'wis_water_frost08', caption: 'Оледенение [8]', spendsMove: true,
		action: 'Мгновенно наносит цели 51 урона и ещё 7 за четыре хода.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		consumes: {mana:70},
		delay: 1,
		attack: {damage:51,nextdamage:7,nextturns:4}
	},
	wis_water_frost09: {name: 'wis_water_frost09', caption: 'Оледенение [9]', spendsMove: true,
		action: 'Мгновенно наносит цели 62 урона и ещё 9 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:9,intellect:60,watermagicskill:9},
		consumes: {mana:84},
		delay: 1,
		attack: {damage:62,nextdamage:9,nextturns:4}
	},
	wis_water_frost10: {name: 'wis_water_frost10', caption: 'Оледенение [10]', spendsMove: true,
		action: 'Мгновенно наносит цели 75 урона и ещё 11 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:10,intellect:75,watermagicskill:10},
		consumes: {mana:101},
		delay: 1,
		attack: {damage:75,nextdamage:11,nextturns:4}
	},
	wis_water_frost11: {name: 'wis_water_frost11', caption: 'Оледенение [11]', spendsMove: true,
		action: 'Мгновенно наносит цели 90 урона и ещё 14 за четыре хода.', iname: 'wis_water_frost08', school: 'water',
		required: {level:11,intellect:100,watermagicskill:11},
		consumes: {mana:121},
		delay: 1,
		attack: {damage:90,nextdamage:14,nextturns:4}
	},
	wis_water_poison06: {name: 'wis_water_poison06', caption: 'Отравление [6]', 
		action: 'Наносит цели 81 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:6,intellect:30,watermagicskill:6},
		consumes: {mana:34},
		delay: 3,
		attack: {nextdamage:81,nextturns:10}
	},
	wis_water_poison07: {name: 'wis_water_poison07', caption: 'Отравление [7]', 
		action: 'Наносит цели 97 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		consumes: {mana:52},
		delay: 3,
		attack: {nextdamage:97,nextturns:10}
	},
	wis_water_poison08: {name: 'wis_water_poison08', caption: 'Отравление [8]', 
		action: 'Наносит цели 117 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		consumes: {mana:62},
		delay: 3,
		attack: {nextdamage:117,nextturns:10}
	},
	wis_water_poison09: {name: 'wis_water_poison09', caption: 'Отравление [9]', 
		action: 'Наносит цели 139 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:9,intellect:60,watermagicskill:9},
		consumes: {mana:74},
		delay: 3,
		attack: {nextdamage:139,nextturns:10}
	},
	wis_water_poison10: {name: 'wis_water_poison10', caption: 'Отравление [10]', 
		action: 'Наносит цели 168 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:10,intellect:75,watermagicskill:10},
		consumes: {mana:89},
		delay: 3,
		attack: {nextdamage:168,nextturns:10}
	},
	wis_water_poison11: {name: 'wis_water_poison11', caption: 'Отравление [11]', 
		action: 'Наносит цели 202 урона ядом за десять ходов. Заклинание требует ману каждый ход.', iname: 'wis_water_poison08', school: 'water',
		required: {level:11,intellect:100,watermagicskill:11},
		consumes: {mana:107},
		delay: 3,
		attack: {nextdamage:202,nextturns:10}
	},
	wis_water_regen05: {name: 'wis_water_regen05', caption: 'Регенерация [5]', 
		action: 'Восстанавливает цели 79НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:5,intellect:20,watermagicskill:5},
		resources: {hp:2},
		consumes: {mana:28},
		delay: 3,
		healing: {nexthitpoints:79,nextturns:8}
	},
	wis_water_regen06: {name: 'wis_water_regen06', caption: 'Регенерация [6]', 
		action: 'Восстанавливает цели 95НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:6,intellect:30,watermagicskill:6},
		resources: {hp:2},
		consumes: {mana:43},
		delay: 3,
		healing: {nexthitpoints:95,nextturns:8}
	},
	wis_water_regen07: {name: 'wis_water_regen07', caption: 'Регенерация [7]',
	 	action: 'Восстанавливает цели 115НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		resources: {hp:2},
		consumes: {mana:65},
		delay: 3,
		healing: {nexthitpoints:115,nextturns:8}
	},
	wis_water_regen08: {name: 'wis_water_regen08', caption: 'Регенерация [8]', 
		action: 'Восстанавливает цели 138НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		resources: {hp:2},
		consumes: {mana:78},
		delay: 3,
		healing: {nexthitpoints:138,nextturns:8}
	},
	wis_water_regen09: {name: 'wis_water_regen09', caption: 'Регенерация [9]', 
		action: 'Восстанавливает цели 166НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:9,intellect:60,watermagicskill:9},
		resources: {hp:2},
		consumes: {mana:93},
		delay: 3,
		healing: {nexthitpoints:166,nextturns:8}
	},
	wis_water_regen10: {name: 'wis_water_regen10', caption: 'Регенерация [10]', 
		action: 'Восстанавливает цели 200НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:10,intellect:75,watermagicskill:10},
		resources: {hp:2},
		consumes: {mana:112},
		delay: 3,
		healing: {nexthitpoints:200,nextturns:8}
	},
	wis_water_regen11: {name: 'wis_water_regen11', caption: 'Регенерация [11]', 
		action: 'Восстанавливает цели 240НР за восемь ходов магией воды. Заклинание требует ману каждый ход', iname: 'wis_water_regen08', school: 'water',
		required: {level:11,intellect:100,watermagicskill:11},
		resources: {hp:2},
		consumes: {mana:134},
		delay: 3,
		healing: {nexthitpoints:240,nextturns:8}
	},
	wis_water_mark: {name: 'wis_water_mark', caption: 'Цель Воды', 
		action: 'Уменьшает сопротивляемость воздействию Магии Воды.<br />Можно применить на одну цель до 5 раз.', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		resources: {},
		delay: 1,
		consumes: {mana:20,spiritlevel:0.5}
	},
	wis_water_sign: {name: 'wis_water_sign', caption: 'Знак Воды', 
		action: 'Маг получает +50 мф. антикрита (показатель зависит от интеллекта).<br />Заклинание требует маны каждый ход.', school: 'water',
		required: {level:4,intellect:25,watermagicskill:2},
		resources: {},
		consumes: {mana:110,spiritlevel:1}
	},
	wis_water_shield7: {name: 'wis_water_shield7', caption: 'Иней [7]', 
		action: 'Вы получаете на 25% меньше урона 4 последующих размена.', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		resources: {hp: 1},
		delay: 8,
		consumes: {mana:100}
	},
	wis_water_shield8: {name: 'wis_water_shield8', caption: 'Иней [8]', 
		action: 'Вы получаете на 25% меньше урона 4 последующих размена,<br>атакующий оружием получает уязвимость к магии воды.<br />Не подвержен действию шока', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		resources: {hp: 1},
		delay: 8,
		consumes: {mana:150}
	},
	wis_water_shield9: {name: 'wis_water_shield9', caption: 'Иней [9]', 
		action: 'Вы получаете на 15% меньше урона 4 последующих размена,<br>атакующий оружием получает уязвимость к магии воды<br />и часть поглощённого урона.<br />Не подвержен действию шока', school: 'water',
		required: {level:9,intellect:60,watermagicskill:9},
		resources: {hp: 1},
		delay: 8,
		consumes: {mana:220}
	},
	wis_water_shield10: {name: 'wis_water_shield10', caption: 'Иней [10]', 
		action: 'Вы получаете на 20% меньше урона 4 последующих размена,<br>атакующий оружием получает уязвимость к магии воды<br />и часть поглощённого урона.<br />Не подвержен действию шока', school: 'water',
		required: {level:10,intellect:75,watermagicskill:10},
		resources: {hp: 1},
		delay: 8,
		consumes: {mana:250}
	},
	wis_water_shield11: {name: 'wis_water_shield11', caption: 'Иней [11]',
		action: 'Вы получаете на 25% меньше урона 4 последующих размена,<br>атакующий оружием получает уязвимость к магии воды<br />и часть поглощённого урона.<br />Не подвержен действию шока', school: 'water',
		required: {level:11,intellect:100,watermagicskill:11},
		resources: {hp: 1},
		delay: 8,
		consumes: {mana:275}
	},
	wis_gray_beam: {name: 'wis_gray_beam', caption: 'Силовой луч', spendsMove: true,
		action: 'Наносит цели урон равный интеллекту мага', school: 'grey',
		required: {level:7,intellect:40,greymagicskill:4},
		delay: 10,
		consumes: {mana:5}
	},
	wis_gray_meditation: {name: 'wis_gray_meditation', caption: 'Медитация', spendsMove: true,
		action: 'Восстанавливает 10% маны.', school: 'grey',
		required: {level:7,intellect:50,greymagicskill:3},
		resources: {},
		consumes: {spiritlevel:2}
	},
	wis_gray_forcefield07: {name: 'wis_gray_forcefield07', caption: 'Силовое Поле [7]', 
		action: 'Создает силовое поле вокруг мага, способное поглотить 120 ед. урона.<br />Нанести критический удар оружием по силовому полю - невозможно', iname: 'wis_gray_forcefield08', school: 'grey',
		required: {level:7,intellect:40,greymagicskill:2},
		delay: 8,
		consumes: {mana:150}
	},
	wis_gray_forcefield08: {name: 'wis_gray_forcefield08', caption: 'Силовое Поле [8]', 
		action: 'Создает силовое поле вокруг мага, способное поглотить 144 ед. урона.<br />Нанести критический удар оружием по силовому полю - невозможно', iname: 'wis_gray_forcefield08', school: 'grey',
		required: {level:8,intellect:50,greymagicskill:3},
		resources: {},		
		delay: 8,
		consumes: {mana:180,spiritlevel:1}
	},
	wis_gray_forcefield09: {name: 'wis_gray_forcefield09', caption: 'Силовое Поле [9]', 
		action: 'Создает силовое поле вокруг мага, способное поглотить 172 ед. урона.<br />Нанести критический удар оружием по силовому полю - невозможно', iname: 'wis_gray_forcefield08', school: 'grey',
		required: {level:9,intellect:60,greymagicskill:4},
		resources: {},
		delay: 8,
		consumes: {mana:216,spiritlevel:2}
	},
	wis_gray_forcefield10: {name: 'wis_gray_forcefield10', caption: 'Силовое Поле [10]', 
		action: 'Создает силовое поле вокруг мага, способное поглотить 207 ед. урона.<br />Нанести критический удар оружием по силовому полю - невозможно', iname: 'wis_gray_forcefield08', school: 'grey',
		required: {level:10,intellect:75,greymagicskill:5},
		resources: {},
		delay: 8,
		consumes: {mana:259,spiritlevel:3}
	},
	wis_gray_forcefield11: {name: 'wis_gray_forcefield11', caption: 'Силовое Поле [11]', 
		action: 'Создает силовое поле вокруг мага, способное поглотить 248 ед. урона.<br />Нанести критический удар оружием по силовому полю - невозможно', iname: 'wis_gray_forcefield08', school: 'grey',
		required: {level:11,intellect:100,greymagicskill:6},
		resources: {},
		delay: 8,
		consumes: {mana:311,spiritlevel:4}
	},
	wis_gray_manabarrier04: {name: 'wis_gray_manabarrier04', caption: 'Магический Барьер [4]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить 352 ед. урона,<br />ценой 2 ед. маны за каждую единицу урона.<br />Барьер поглощает лишь половину повреждений.<br />Этот прием не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:4,wisdom:10,intellect:30},		
		consumes: {mana:5}
	},
	wis_gray_manabarrier07: {name: 'wis_gray_manabarrier07', caption: 'Магический Барьер [7]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить урон,<br />равный 33% от максимального количества маны,<br />ценой 1.8 ед. маны за каждую единицу урона.<br />Барьер поглощает 55% повреждений.<br />Шанс нанести критический удар по барьеру уменьшен на 14%.<br />Этот приём не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:7,intellect:40},
		consumes: {mana:15}
	},
	wis_gray_manabarrier08: {name: 'wis_gray_manabarrier08', caption: 'Магический Барьер [8]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить урон,<br />равный 33% от максимального количества маны,<br />ценой 1.6 ед. маны за каждую единицу урона.<br />Барьер поглощает 60% повреждений.<br />Шанс нанести критический удар по барьеру уменьшен на 16%.<br />Этот приём не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:8,intellect:50},
		consumes: {mana:15}
	},
	wis_gray_manabarrier09: {name: 'wis_gray_manabarrier09', caption: 'Магический Барьер [9]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить урон,<br />равный 33% от максимального количества маны,<br />ценой 1.5 ед. маны за каждую единицу урона.<br />Барьер поглощает 65% повреждений.<br />Шанс нанести критический удар по барьеру уменьшен на 18%.<br />Этот приём не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:9,intellect:60},
		consumes: {mana:15}
	},
	wis_gray_manabarrier10: {name: 'wis_gray_manabarrier10', caption: 'Магический Барьер [10]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить урон,<br />равный 33% от максимального количества маны,<br />ценой 1.5 ед. маны за каждую единицу урона.<br />Барьер поглощает 70% повреждений.<br />Шанс нанести критический удар по барьеру уменьшен на 20%.<br />Этот приём не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:10,intellect:75},
		consumes: {mana:15}
	},
	wis_gray_manabarrier11: {name: 'wis_gray_manabarrier11', caption: 'Магический Барьер [11]', 
		action: 'Создает магический барьер вокруг мага, способный поглотить урон,<br />равный 33% от максимального количества маны,<br />ценой 1.8 ед. маны за каждую единицу урона.<br />Барьер поглощает 75% повреждений.<br />Шанс нанести критический удар по барьеру уменьшен на 22%.<br />Этот приём не подвержен действию шока.', iname: 'wis_gray_manabarrier2', school: 'grey',
		required: {level:11,intellect:100},
		consumes: {mana:15}
	},
	wis_gray_mastery: {name: 'wis_gray_mastery', caption: 'Серое Мастерство', 
		action: 'Увеличивает навык в магии стихий, применяется до 5 раз.<br />Тратит 5*(уровень заклинания) маны за ход', school: 'grey',
		required: {level:7,intellect:40,greymagicskill:4},
		resources: {},
		delay: 5,
		consumes: {mana:5,spiritlevel:2}
	},
	/*wis_gray_beam01: {name: 'wis_gray_beam01', caption: 'Магический луч', description: 'Наносит цели 7*(ваш уровень) ед. урона серой магией.', iname: 'wis_gray_beam', school: 'grey',
		required: {level:4,intellect:30},
		consumes: {mana:50}
	},*/
	wis_light_heal04: {name: 'wis_light_heal04', caption: 'Магическое исцеление', 
		action: 'Исцеляет мага на 50НР, не тратя силы духа.', iname: 'wis_light_heal07', school: 'light',
		required: {level:4,intellect:30},
		delay: 5,
		consumes: {mana:125}
	},
	wis_light_cleance: {name: 'wis_light_cleance', caption: 'Очищение', 
		action: 'Снимает один негативный эффект проклятья, болезни или отравления.', school: 'light',
		required: {level:8,intellect:50,lightmagicskill:5},
		delay: 5,
		consumes: {mana:100}
	},
	wis_light_damage07: {name: 'wis_light_damage07', caption: 'Усмирение [7]', spendsMove: true,
		action: 'Наносит цели 42 урона магией Света, цель теряет характеристики на несколько ходов.', iname: 'wis_light_damage08', school: 'light',
		required: {level:7,intellect:40,lightmagicskill:2},
		consumes: {mana:58,spiritlevel:1},
		resources: {},
		delay: 1,
		attack: {damage:42}
	},
	wis_light_damage08: {name: 'wis_light_damage08', caption: 'Усмирение [8]', spendsMove: true,
		action: 'Наносит цели 50 урона магией Света, цель теряет характеристики на несколько ходов.', iname: 'wis_light_damage08', school: 'light',
		required: {level:8,intellect:50,lightmagicskill:3},
		consumes: {mana:70,spiritlevel:1},
		resources: {},
		delay: 1,
		attack: {damage:50}
	},
	wis_light_damage09: {name: 'wis_light_damage09', caption: 'Усмирение [9]', spendsMove: true,
		action: 'Наносит цели 61 урона магией Света, цель теряет характеристики на несколько ходов.', iname: 'wis_light_damage08', school: 'light',
		required: {level:9,intellect:60,lightmagicskill:4},
		consumes: {mana:84,spiritlevel:1},
		resources: {},
		delay: 1,
		attack: {damage:61}
	},
	wis_light_damage10: {name: 'wis_light_damage10', caption: 'Усмирение [10]', spendsMove: true,
		action: 'Наносит цели 73 урона магией Света, цель теряет характеристики на несколько ходов.', iname: 'wis_light_damage08', school: 'light',
		required: {level:10,intellect:75,lightmagicskill:5},
		consumes: {mana:101,spiritlevel:1},
		resources: {},
		delay: 1,
		attack: {damage:73}
	},
	wis_light_damage11: {name: 'wis_light_damage11', caption: 'Усмирение [11]', spendsMove: true,
		action: 'Наносит цели 87 урона магией Света, цель теряет характеристики на несколько ходов.', iname: 'wis_light_damage08', school: 'light',
		required: {level:11,intellect:100,lightmagicskill:6},
		consumes: {mana:121,spiritlevel:1},
		resources: {},
		delay: 1,
		attack: {damage:87}
	},
	wis_light_heal07: {name: 'wis_light_heal07', caption: 'Лечение [7]', spendsMove: true,
		action: 'Исцеляет цель на 183 НР магией Света.', iname: 'wis_light_heal08', school: 'light',
		required: {level:7,intellect:40,lightmagicskill:2},
		resources: {hp:1},
		consumes: {mana:117},
		delay: 1,
		healing: {hitpoints:183}
	},
	wis_light_heal08: {name: 'wis_light_heal08', caption: 'Лечение [8]', spendsMove: true,
		action: 'Исцеляет цель на 219НР магией Света.', iname: 'wis_light_heal08', school: 'light',
		required: {level:8,intellect:50,lightmagicskill:3},
		resources: {hp:1},
		consumes: {mana:140},
		delay: 1,
		healing: {hitpoints:219}
	},
	wis_light_heal09: {name: 'wis_light_heal09', caption: 'Лечение [9]', spendsMove: true,
		action: 'Исцеляет цель на 263НР магией Света.', iname: 'wis_light_heal08', school: 'light',
		required: {level:9,intellect:60,lightmagicskill:4},
		resources: {hp:1},
		consumes: {mana:168},
		delay: 1,
		healing: {hitpoints:263}
	},
	wis_light_heal10: {name: 'wis_light_heal10', caption: 'Лечение [10]', spendsMove: true,
		action: 'Исцеляет цель на 316НР магией Света.', iname: 'wis_light_heal08', school: 'light',
		required: {level:10,intellect:75,lightmagicskill:5},
		resources: {hp:1},
		consumes: {mana:202},
		delay: 1,
		healing: {hitpoints:316}
	},
	wis_light_heal11: {name: 'wis_light_heal11', caption: 'Лечение [11]', spendsMove: true,
		action: 'Исцеляет цель на 380НР магией Света.', iname: 'wis_light_heal08', school: 'light',
		required: {level:11,intellect:100,lightmagicskill:6},
		resources: {hp:1},
		consumes: {mana:242},
		delay: 1,
		healing: {hitpoints:380}
	},
	wis_light_insight07: {name: 'wis_light_insight07', caption: 'Прозрение [7]', spendsMove: true,
		action: 'Восстанавливает 552 маны за 20 ходов.', iname: 'wis_light_insight', school: 'light',
		required: {level:7,intellect:40,lightmagicskill:2},
		resources: {},
		delay: 20,
		consumes: {mana:312,spiritlevel:5}
	},
	wis_light_insight08: {name: 'wis_light_insight08', caption: 'Прозрение [8]', spendsMove: true,
		action: 'Восстанавливает 662 маны за 20 ходов.', iname: 'wis_light_insight', school: 'light',
		required: {level:8,intellect:50,lightmagicskill:3},
		resources: {},
		delay: 20,
		consumes: {mana:374,spiritlevel:5}
	},
	wis_light_insight09: {name: 'wis_light_insight09', caption: 'Прозрение [9]', spendsMove: true,
		action: 'Восстанавливает 794 маны за 20 ходов.', iname: 'wis_light_insight', school: 'light',
		required: {level:9,intellect:60,lightmagicskill:4},
		resources: {},
		delay: 20,
		consumes: {mana:449,spiritlevel:5}
	},
	wis_light_insight10: {name: 'wis_light_insight10', caption: 'Прозрение [10]', spendsMove: true,
		action: 'Восстанавливает 953 маны за 20 ходов.', iname: 'wis_light_insight', school: 'light',
		required: {level:10,intellect:75,lightmagicskill:5},
		resources: {},
		delay: 20,
		consumes: {mana:539,spiritlevel:5}
	},
	wis_light_insight11: {name: 'wis_light_insight11', caption: 'Прозрение [11]', spendsMove: true,
		action: 'Восстанавливает 1144 маны за 20 ходов.', iname: 'wis_light_insight', school: 'light',
		required: {level:11,intellect:100,lightmagicskill:6},
		resources: {},
		delay: 20,
		consumes: {mana:646,spiritlevel:5}
	},
	wis_light_shield: {name: 'wis_light_shield', caption: 'Защита Света', 
		action: 'Снижает весь урон получаемый магом на 15%<br />и повышает эфективность лечения на 10% на 10 ходов.', iname: 'wis_light_shield', school: 'light',
		required: {level:7,intellect:40,lightmagicskill:4},
		delay: 20,
		consumes: {mana:200}
	},
	wis_dark_soulweak: {name: 'wis_dark_soulweak', caption: 'Слабость Духа', 
		action: 'На 3 хода все заклинания цели стоят дороже, а физический урон сокращён.<br />Цель получает иммунитет к этому заклинанию на 10 ходов', school: 'dark',
		required: {level:8,intellect:50,darkmagicskill:5},
		delay: 5,
		consumes: {mana:100}
	},
	wis_dark_souleat: {name: 'wis_dark_souleat', caption: 'Поглотить', 
		action: 'Вы поглощаете дух павшего в бою, восстанавливая себя.<br />Восстанавливает 5* Уровень НР и 10* Уровень маны.<br />Одну цель можно поглотить только один раз.<br />Заклятие не влияет на уровень духа цели.', school: 'dark',
		required: {level:8,intellect:50,darkmagicskill:5},
		delay: 5,
		consumes: {mana:50}
	},
	wis_dark_damage07: {name: 'wis_dark_damage07', caption: 'Разрушение [7]', spendsMove: true,
		action: 'Наносит цели 33 урона магией Тьмы, часть урона лечит мага.', iname: 'wis_dark_damage08', school: 'dark',
		required: {level:7,intellect:40,darkmagicskill:5},
		consumes: {mana:58},
		attack: {damage:33}
	},
	wis_dark_damage08: {name: 'wis_dark_damage08', caption: 'Разрушение [8]', spendsMove: true,
		action: 'Наносит цели 39 урона магией Тьмы, часть урона лечит мага.', iname: 'wis_dark_damage08', school: 'dark',
		required: {level:8,intellect:50,darkmagicskill:6},
		consumes: {mana:70},
		attack: {damage:39}
	},
	wis_dark_damage09: {name: 'wis_dark_damage09', caption: 'Разрушение [9]', spendsMove: true,
		action: 'Наносит цели 47 урона магией Тьмы, часть урона лечит мага.', iname: 'wis_dark_damage08', school: 'dark',
		required: {level:9,intellect:60,darkmagicskill:7},
		consumes: {mana:84},
		attack: {damage:47}
	},
	wis_dark_damage10: {name: 'wis_dark_damage10', caption: 'Разрушение [10]', spendsMove: true,
		action: 'Наносит цели 57 урона магией Тьмы, часть урона лечит мага.', iname: 'wis_dark_damage08', school: 'dark',
		required: {level:10,intellect:75,darkmagicskill:8},
		consumes: {mana:101},
		attack: {damage:57}
	},
	wis_dark_damage11: {name: 'wis_dark_damage11', caption: 'Разрушение [11]', spendsMove: true,
		action: 'Наносит цели 69 урона магией Тьмы, часть урона лечит мага.', iname: 'wis_dark_damage08', school: 'dark',
		required: {level:11,intellect:100,darkmagicskill:9},
		consumes: {mana:121},
		attack: {damage:69}
	},
	wis_dark_manadamage07: {name: 'wis_dark_manadamage07', caption: 'Опустошение [7]', spendsMove: true,
		action: 'Лишает цель 244 маны при помощи магии Тьмы,<br />лишая цель возможности использовать последний применённый приём и все приёмы того же класса на 3 хода.<br />Цель получает иммунитет к Опустошению на 10 ходов.', iname: 'wis_dark_manadamage08', school: 'dark',
		required: {level:7,intellect:40,darkmagicskill:5},
		resources: {hp:2},
		consumes: {mana:130},
		delay: 5,
		attack: {manadamage:244}
	},
	wis_dark_manadamage08: {name: 'wis_dark_manadamage08', caption: 'Опустошение [8]', spendsMove: true,
		action: 'Лишает цель 292 маны при помощи магии Тьмы,<br />лишая цель возможности использовать последний применённый приём и все приёмы того же класса на 3 хода.<br>Цель получает иммунитет к Опустошению на 10 ходов.', iname: 'wis_dark_manadamage08', school: 'dark',
		required: {level:8,intellect:50,darkmagicskill:6},
		resources: {hp:2},
		consumes: {mana:156},
		delay: 5,
		attack: {manadamage:292}
	},
	wis_dark_manadamage09: {name: 'wis_dark_manadamage09', caption: 'Опустошение [9]', spendsMove: true,
		action: 'Лишает цель 351 маны при помощи магии Тьмы,<br />лишая цель возможности использовать последний применённый приём и все приёмы того же класса на 3 хода.<br>Цель получает иммунитет к Опустошению на 10 ходов.', iname: 'wis_dark_manadamage08', school: 'dark',
		required: {level:9,intellect:60,darkmagicskill:7},
		resources: {hp:2},
		consumes: {mana:187},
		delay: 5,
		attack: {manadamage:351}
	},
	wis_dark_manadamage10: {name: 'wis_dark_manadamage10', caption: 'Опустошение [10]', spendsMove: true,
		action: 'Лишает цель 412 маны при помощи магии Тьмы,<br />лишая цель возможности использовать последний применённый приём и все приёмы того же класса на 3 хода.<br>Цель получает иммунитет к Опустошению на 10 ходов.', iname: 'wis_dark_manadamage08', school: 'dark',
		required: {level:10,intellect:75,darkmagicskill:8},
		resources: {hp:2},
		consumes: {mana:224},
		delay: 5,
		attack: {manadamage:421}
	},
	wis_dark_manadamage11: {name: 'wis_dark_manadamage11', caption: 'Опустошение [11]', spendsMove: true,
		action: 'Лишает цель 506 маны при помощи магии Тьмы,<br />лишая цель возможности использовать последний применённый приём и все приёмы того же класса на 3 хода.<br>Цель получает иммунитет к Опустошению на 10 ходов.', iname: 'wis_dark_manadamage08', school: 'dark',
		required: {level:11,intellect:100,darkmagicskill:9},
		resources: {hp:2},
		consumes: {mana:269},
		delay: 5,
		attack: {manadamage:506}
	},
	wis_dark_eyeforeye: {name: 'wis_dark_eyeforeye', caption: 'Глаз за глаз', 
		action: 'Следующее заклинание или удар нанесет не более половины урона,<br />оставшуюся половину магией тьмы получит атакующий<br />(но не более 50*ваш уровень ед. урона).', iname: 'wis_dark_eyeforeye', school: 'dark',
		required: {level:7,intellect:40,darkmagicskill:4},
		delay: 10,
		consumes: {mana:200}
	},
	wis_air_charge: {name: 'wis_air_charge', caption: 'Статика', 
		action: 'Молния, Цепь молний, Искра, Искры, и удары по Воздушному Щиту будут заряжать цель, увеличивая получаемый от магии Воздуха урон на 1%.<br />Маг может воспользоваться накопленными зарядами.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		delay: 3,
		consumes: {mana:25,spiritlevel:1}
	},
	wis_air_charge_shock: {name: 'wis_air_charge_shock', caption: 'Заряд: Шок', 
		action: 'Шокирует противника, лишая его возможности использовать последний примененный прием на 5 ходов и рассеивает один позитивный магический эффект.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		delay: 5,
		resources: {hp:1}
	},
	wis_air_charge_gain: {name: 'wis_air_charge_gain', caption: 'Заряд: Собрать', 
		action: 'Восстанавливает 3* (уровень персонажа) маны за каждый уровень заряда на цели и снимает один негативный магический эффект.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		delay: 3,
		resources: {hp:1}
	},
	wis_air_charge_dmg: {name: 'wis_air_charge_dmg', caption: 'Заряд: Поражение', 
		action: 'Наносит цели 1-3% урона магией Воздуха от ее максимального уровня жизни за каждый уровень Заряда.<br>Заклинание не может нанести более 250 ед. урона для 9го уровня.<br>Заклинание не может нанести более 300 ед. урона для 10го уровня.<br>Заклинание не может нанести более 350 ед. урона для 11го уровня.', iname: 'wis_air_charge_dmg', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		delay: 3,
		resources: {hp:1}
	},
	wis_air_manaheal: {name: 'wis_air_manaheal', caption: 'Энергия Воздуха', 
		action: 'Восстанавливает цели 1-10% маны за каждый ход работы заклинания.<br />Заклинание прекращает действие при использовании любого другого заклинания или через 5 ходов.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:11},
		resources: {hp:1},
		delay: 10,
		consumes: {spiritlevel:3}
	},
	wis_air_sacrifice: {name: 'wis_air_sacrifice', caption: 'Жертва Воздуху', 
		action: 'Маг получает 25 мф. мощности магии Воздуха на 4 хода.<br />Снимается приемом Очистится кровью.', school: 'air',
		required: {level:7,intellect:40,airmagicskill:7},
		resources: {hp:5},
		delay: 10,
		consumes: {mana:10}
	},
	wis_air_speed: {name: 'wis_air_speed', caption: 'Скорость Молнии', 
		action: 'Любой следующий прием не тратит хода.', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		resources: {},
		delay: 10,
		beginDelay: 10,
		consumes: {mana:85,spiritlevel:4}
	},
	wis_air_spark: {name: 'wis_air_spark', caption: 'Искра', 
		action: 'Мгновенно наносит цели 1-100 урона воздухом или исцеляет дружественную цель.', school: 'air',
		required: {level:8,intellect:50,airmagicskill:8},
		delay: 10,
		consumes: {mana:121}
	},
	/*wis_air_shield: {name: 'wis_air_shield', caption: 'Воздушный Щит', description: 'Создаёт воздушный кокон вокруг мага, способный поглотить 1-? ед. урона. Этот приём не подвержен действию шока. Общая задержка с заклинанием Силовое поле.', school: 'air',
		required: {level:9,intellect:60,airmagicskill:9},
		consumes: {mana:172}
	},*/
	wis_water_tempheal: {name: 'wis_water_tempheal', caption: 'Ледяное Спасение', 
		action: 'Мгновенно останавливает кровотечения, исцеляя мага на ???HP магией воды,<br />но за 5 ходов теряет 50% полученного здоровья.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		resources: {hp:1},
		delay: 5,
		consumes: {mana:168}
	},
	wis_water_break: {name: 'wis_water_break', caption: 'Оледенениие: Разбить!', spendsMove: true,
		action: 'Наносит текущей цели подверженной Оледенению 144 урона магией воды.<br />Урон увеличен на 50% за каждый уровень оледенения,<br />если НР цели менее 33%.', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		delay: 5,
		consumes: {mana:191}
	},
	wis_water_crystalize: {name: 'wis_water_crystalize', caption: 'Кристаллизация', 
		action: 'Мгновенно наносит цели урон равный уровню силы цели, но не более чем 10*(ваш уровень).<br />Снижает силу и ловкость цели на (количество владений водой) на три хода.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		delay: 5,
		consumes: {mana:200}
	},
	wis_water_icegrap: {name: 'wis_water_icegrap', caption: 'Хватка Льда', 
		action: 'Через 2 хода цель теряет возможность использовать приемы или набирать очки тактики на два хода.<br />Работает только на целях, подверженных Оледенению', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		delay: 10,
		consumes: {mana:100}
	},
	wis_water_spirit: {name: 'wis_water_spirit', caption: 'Духи Льда', 
		action: 'На три хода увеличивает мф. мощности Магии Воды на 15. Часть вашего прямого урона Магией Воды восстанавливает вашу ману.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		resources: {hp:4},
		delay: 10,
		consumes: {mana:5, spiritlevel:5}
	},
	wis_water_aheal: {name: 'wis_water_aheal', caption: 'Переохлаждение', 
		action: 'Уменьшает эффекты лечения на цели на 10% на 5 ходов.<br />Можно применить на одну цель до 3 раз.', school: 'water',
		required: {level:9,intellect:75,watermagicskill:9},
		resources: {hp:1},
		consumes: {mana:70}
	},
	wis_water_cleance: {name: 'wis_water_cleance', caption: 'Чистота Воды', 
		action: 'Снимает один негативный эффект магии или отравления.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		delay: 5,
		consumes: {mana:100}
	},
	wis_water_hiddenpower: {name: 'wis_water_hiddenpower', caption: 'Ледяное Сердце', 
		action: 'При использовании убирает текущие задержки на заклинаниях школы Воды.<br />Не подвержен действию шока.', school: 'water',
		required: {level:8,intellect:50,watermagicskill:8},
		delay: 10,
		beginDelay: 5,
		consumes: {mana:200}
	},
	wis_water_sacrifice: {name: 'wis_water_sacrifice', caption: 'Жертва Воде', 
		action: 'Маг теряет 10% жизни за 5 ходов, но цена всех заклятий снижена на 50%.', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		resources: {hp:5},
		delay: 10,
		consumes: {mana:5}
	},
	wis_water_strike: {name: 'wis_water_strike', caption: 'Острая Грань', spendsMove: true,
		action: 'Наносит цели 485 ед. колющего урона.', school: 'water',
		required: {level:7,intellect:40,watermagicskill:7},
		delay: 3,
		consumes: {mana:162}
	} 
 };
 
